In [1]:
# Import required libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [2]:
# Load Titanic dataset

df = pd.read_csv("titanic.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# Select required columns
# Fill missing values with the median

X = df[["Age", "Fare", "Pclass", "SibSp", "Parch"]].copy()

X = X.fillna(X.median())

# Target variable
y = df["Survived"]

X.head()

    Age     Fare  Pclass  SibSp  Parch
0  22.0   7.2500       3      1      0
1  38.0  71.2833       1      1      0
2  26.0   7.9250       3      0      0
3  35.0  53.1000       1      1      0
4  35.0   8.0500       3      0      0

In [4]:
# 80% training data and 20% testing data

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)